# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hangmeout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hangmeout

  # target 'hangmeout-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'hangmeoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hangmeout-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hangmeout-tvOS

  target 'hangmeout-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
